services:
  development:
    image: sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.12_8_1.13.0_2.12.21@sha256:6f4acfdfdfb6dc54754d4356c69967b373aaf6016ab568435c3bc11d1cb8851c
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ~/.cache
        target: /root/.cache
      - type: bind
        source: ~/.ivy2
        target: /root/.ivy2
      - type: bind
        source: ~/.sbt
        target: /root/.sbt
    working_dir: /app
