services:
  development:
    image: sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.11_10_1.12.11_3.3.7@sha256:999851fff0eae2256c3f4ba45c7ff6644144b589147d022afaa7a5cc7a5ce907
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ~/.cache
        target: /root/.cache
      - type: bind
        source: ~/.ivy2
        target: /root/.ivy2
      - type: bind
        source: ~/.sbt
        target: /root/.sbt
    working_dir: /app
