name: On Push

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780 # v3.0.0
        with:
          distribution: temurin
          # renovate: datasource=java-version packageName=java
          java-version: 21.0.10+7.0.LTS

      - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19

      - name: Run compile and tests
        shell: bash
        run: sbt --verbose "+test"
